services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0-legacy
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: password
    ports:
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
  service1-backend:
    build:
      context: ./service1/backend
      dockerfile: "Dockerfile.dev"
    volumes:
      - ./service1/backend:/app:cached
    ports:
      - 8000:8000
    depends_on:
      - keycloak

volumes:
  postgres-data:
